{% set name = "rafem" %}
{% set version = "0.2.1" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://github.com/mcflugen/avulsion-bmi/archive/v{{ version }}.tar.gz
  fn: avulsion-bmi-{{ version }}.tar.gz
  sha256: ece32fbfd3db559170e92f0f0e8d83a5ff889fabe5a059856e76582c80dce16e

requirements:
  build:
    - python
    - numpy
    - nose
    - model_metadata
  run:
    - python
    - numpy
    - pyyaml
    - scipy
    - nose

build:
  number: 0
  script: python -m pip install --no-deps --ignore-installed .

test:
  imports:
    - rafem
  # commands:
  #   - nosetests --with-doctest rafem

about:
  home: https://github.com/katmratliff/avulsion-bmi
  license: MIT
  summary: |
    Morphodynamic river avulsion module designed to be coupled with
    the Coastline Evolution Model (CEM) and Sedflux 3D.
  dev_url: https://github.com/katmratliff/avulsion-bmi
