{% set name = "rafem" %}
{% set version = "0.3" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://github.com/mcflugen/avulsion-bmi/archive/v{{ version }}.tar.gz
  fn: avulsion-bmi-{{ version }}.tar.gz
  sha256: 4ce17749727822ec852564b92ea0726e413713f7a2a58d592db75508cfc742d2

requirements:
  build:
    - python
    - numpy
    - nose
    - model_metadata
  run:
    - python
    - numpy
    - pyyaml
    - scipy
    - nose

build:
  number: 0
  script: python -m pip install --no-deps --ignore-installed .

test:
  requires:
    - model_metadata
    - bmi-tester
  imports:
    - rafem
  commands:
    - mmd-stage BmiRiverModule .
    - bmi-test rafem:BmiRiverModule --infile=input.yaml
  # commands:
  #   - nosetests --with-doctest rafem

about:
  home: https://github.com/katmratliff/avulsion-bmi
  license: MIT
  summary: |
    Morphodynamic river avulsion module designed to be coupled with
    the Coastline Evolution Model (CEM) and Sedflux 3D.
  dev_url: https://github.com/katmratliff/avulsion-bmi
