language: generic
os:
- linux
- osx
env:
  matrix:
  - TRAVIS_PYTHON_VERSION="2.7"
  # - TRAVIS_PYTHON_VERSION="3.5"
  # - TRAVIS_PYTHON_VERSION="3.6"
  # - TRAVIS_PYTHON_VERSION="3.7"
  global:
  - CONDA_PREFIX=$HOME/miniconda
  - MINICONDA_URL_BASE="https://repo.continuum.io/miniconda/Miniconda2-latest"
  - secure: iBA3H+SzodsnMKgm7KZiSsAzFHwXBWMD6Z7A2U4HMzQfh6CCwcAmujxjr2/6z3KJoKy5lBiLd62qWd+8JWguUegLnW5R4z3I/V6upKHqd7N1aApsteEu+uxgVwbvpVa4mmPl4xVVSWOXBG9FVKJ3vSQvi5eut+4Q1Zc57Gp/tTYRy5fHlnhooSpbrxONKE3zvTB0w+Yxjk9AZh5jDorwa8ylLtjU2KzF7B/J000LzZjjHt6jdp19W7Zt8JVubBk4Qz0iKBWf6ddNO3XHCR/YhlAE1l9GRd0gGOEijc+KqsrzO63nahjOFA+ApUVGcetp8IEMoAkw6gNPU3GPHOU+IpkAHvxs2n+yt5bqlKSktdR/Cl3CKIP/USjMs5lK30RW5x9BD4W1q+bEJ7h/EF2iiGVoQIYVVxgfnIPlkOsOYB9lq6xEXCnH057+KFBUH+5q23i1GBvlakgb4rYjTO3QplJJs8DXnzsPuHB9TlDghhmbHi2n8Uep9kKM+1jypLLJ/oyqFu36miJZ63ciOcEBoWKCZh731aYDXDxn4XXbMrBbhzdkaEKvBSCC/N5DCjXqTN518k56m1nof/z6P4098KfCIbpHfplTWD/fk21HOX9IDmqTz/qhpaUTa2Ti3emuBi2DctE4J4OdzZLHtZNherEv7wdPCczYZP6TTSO9sMg=
sudo: false
before_install:
- |
  if [[ $TRAVIS_OS_NAME == "osx" ]]; then
    brew remove --force $(brew list)
    brew cleanup -s
    rm -rf $(brew --cache)
  fi
install:
- |
  if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
    OS="MacOSX-x86_64"
  else
    OS="Linux-x86_64"
  fi
- curl $MINICONDA_URL_BASE-$OS.sh > $HOME/minconda.sh
- bash $HOME/minconda.sh -b -p $CONDA_PREFIX
- export PATH="$CONDA_PREFIX/bin:$PATH"
- hash -r
- conda config --set always_yes yes --set changeps1 no
- conda create -n _testing python=$TRAVIS_PYTHON_VERSION
- source activate _testing
- conda install -q conda-build anaconda-client coverage sphinx
script:
- conda build ./recipe -c csdms-stack -c conda-forge
after_success:
- curl https://raw.githubusercontent.com/csdms/ci-tools/master/anaconda_upload.py
  > $HOME/anaconda_upload.py
- echo $ANACONDA_TOKEN | python $HOME/anaconda_upload.py ./recipe --channel=main --org=csdms-stack
  --token=-
